# Generated by Django 4.0.5 on 2022-06-11 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('icon_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
