# Generated by Django 4.0.5 on 2022-06-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_delete_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('icon_id', models.IntegerField(null=True)),
                ('owner', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('introduction', models.CharField(max_length=100)),
            ],
        ),
    ]
