# Generated by Django 4.0.4 on 2022-06-13 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=32)),
                ('latest_messages', models.CharField(max_length=100)),
                ('friend_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_name', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'unique_together': {('user_name', 'friend_name')},
            },
        ),
    ]
