# Generated by Django 4.0.4 on 2022-06-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_user',
        ),
    ]
