# Generated by Django 4.0.4 on 2022-06-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_delete_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('friend_name', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=32)),
                ('latest_messages', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('user_name', 'friend_name')},
            },
        ),
    ]
