# Generated by Django 4.0.4 on 2022-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('group_name', models.CharField(max_length=30)),
                ('isOwner', models.BooleanField()),
                ('isAdmin', models.BooleanField()),
            ],
            options={
                'unique_together': {('user_name', 'group_name')},
            },
        ),
    ]
